// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcLhMV67a04pmavOApxvP-hoDg8iCRPE',
    appId: '1:464559615412:web:32e057da80a06eb53b96e1',
    messagingSenderId: '464559615412',
    projectId: 'auth-app-a37c7',
    authDomain: 'auth-app-a37c7.firebaseapp.com',
    storageBucket: 'auth-app-a37c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL22Crrkh0wia_2LDqHRF--YaJnZ62V9M',
    appId: '1:464559615412:android:17c0839231600eb53b96e1',
    messagingSenderId: '464559615412',
    projectId: 'auth-app-a37c7',
    storageBucket: 'auth-app-a37c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmjxz3Yag9PhFyDZR0bRHCZUPG3rzzp0',
    appId: '1:464559615412:ios:917791a143cdc9873b96e1',
    messagingSenderId: '464559615412',
    projectId: 'auth-app-a37c7',
    storageBucket: 'auth-app-a37c7.appspot.com',
    iosClientId:
        '464559615412-b16faq780qmfpn8j77fq93f23juoo3s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDmjxz3Yag9PhFyDZR0bRHCZUPG3rzzp0',
    appId: '1:464559615412:ios:917791a143cdc9873b96e1',
    messagingSenderId: '464559615412',
    projectId: 'auth-app-a37c7',
    storageBucket: 'auth-app-a37c7.appspot.com',
    iosClientId:
        '464559615412-b16faq780qmfpn8j77fq93f23juoo3s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );
}
